name: Build A510Player

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          curl -L https://github.com/theos/sdks/archive/master.tar.gz | tar -xz
          mkdir -p $HOME/theos/sdks
          cp -R sdks-master/*.sdk $HOME/theos/sdks/

      - name: Install ldid
        run: |
          brew install ldid
          which ldid
          ldid -h || true

      - name: Build rootless package
        run: |
          export THEOS=$HOME/theos
          make clean package THEOS_PACKAGE_SCHEME=rootless

      - name: Show packages
        run: |
          ls -lah packages/

      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          name: A510Player-DEB
          path: packages/*.deb
